### ISSUE TITLE
Improper error message

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/MonetDBe-Python#63]
**Describe the bug**
Try to execute an empty string should not complain about multiple queries

**To Reproduce**
```
conn = monetdbe.connect(':memory:')
res = conn.execute("""""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ufs/mk/.virtualenvs/python-Kt-6h5O5/lib/python3.7/site-packages/monetdbe/connection.py", line 100, in execute
    cur = Cursor(con=self).execute(query, args)
  File "/ufs/mk/.virtualenvs/python-Kt-6h5O5/lib/python3.7/site-packages/monetdbe/cursor.py", line 142, in execute
    raise Warning("Multiple queries in one execute() call")
monetdbe.exceptions.Warning: Multiple queries in one execute() call
```

**Expected behavior**
Either considered as a no-op or a proper error message

**Software versions**
 - OS and version: OSX 
Python version: 3.7.7
 - MonetDBe-Python version: 0.7.1

**Additional context**

**Comment by gijzelaerr** [comment]
This issue has been resolved.
