### ISSUE TITLE
MonetDBe on windows broken

### ISSUE THREAD

**Issue by gijzelaerr** [MonetDBSolutions/MonetDBe-Python#96]
```
>>> import monetdbe
>>> monetdbe.connect('gijs.db')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gijs\Code\MonetDBe-Python\monetdbe\dbapi2.py", line 48, in connect
    return Connection(*args, **kwargs)
  File "C:\Users\gijs\Code\MonetDBe-Python\monetdbe\connection.py", line 72, in __init__
    self.lowlevel: Optional[MonetEmbedded] = MonetEmbedded(
  File "C:\Users\gijs\Code\MonetDBe-Python\monetdbe\_cffi.py", line 144, in __init__
    self._switch()
  File "C:\Users\gijs\Code\MonetDBe-Python\monetdbe\_cffi.py", line 173, in _switch
    self.set_connection(self.open())
  File "C:\Users\gijs\Code\MonetDBe-Python\monetdbe\_cffi.py", line 214, in open
    raise exceptions.OperationalError(f"Failed to open database: {error} (code {result_code})")
monetdbe.exceptions.OperationalError: Failed to open database: MALException:monetdbe.monetdbe_startup:GDKinit() failed (code -2)
>>> monetdbe.connect()
<monetdbe.connection.Connection object at 0x000001BDBCE726D0>
>>> x = monetdbe.connect()
:memory:: Invalid argument
:memory:: Invalid argument
:memory:: Invalid argument
:memory:: Invalid argument
:memory:: Invalid argument
:memory:: Invalid argument
:memory:: Invalid argument
:memory:: Invalid argument
:memory:: Invalid argument
:memory:: Invalid argument

[Ad infinitum]
```

**Comment by njnes** [comment]
what is the exact string we pass too monetdbe here?

**Comment by gijzelaerr** [comment]
I think that it just `:memory:`, just like on the other platforms. This used to work before.

**Comment by njnes** [comment]
I used to get no 'url'/dbname/dbpath.

**Comment by njnes** [comment]
ie still the case on linux.

**Comment by njnes** [comment]
added small fix on oct2020 branch

**Comment by gijzelaerr** [comment]
in-memory is working now, but supplying a path still raises:
```monetdbe.exceptions.OperationalError: Failed to open database: MALException:monetdbe.monetdbe_startup:GDKinit() failed (code -2)```

**Comment by njnes** [comment]
could you find out what the path/url argument will be once you reach the monetdbe_open call?

**Comment by njnes** [comment]
just tested with c-only version, if proper path is given a open/close pair correctly works, ie i need more details to debug this.

**Comment by gijzelaerr** [comment]
ok don't have time now, but i tested this with a relative path. The folder is created, but empty and `GDKinit()` error.

**Comment by gijzelaerr** [comment]
ok the current status is that in memory works, full path works, but relative paths don't work. If I do:
```
In [1]: from monetdbe import connect                                                                                                                                                                                                                                                                          In [2]: m = connect()                                                                                                                                                                                                                                                                                         In [3]: d = connect('gijs')                                                                                                                                                                                                                                                                                                                                                                                                                                          
````

I get the error:
```
Unhandled exception in event loop:                                                                                                                       File "C:\python38\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading                                                                       f.result()  # may raise                                                                                                                              File "C:\python38\lib\asyncio\windows_events.py", line 808, in _poll                                                                                     value = callback(transferred, key, ov)                                                                                                               File "C:\python38\lib\asyncio\windows_events.py", line 457, in finish_recv                                                                               raise ConnectionResetError(*exc.args)                                                                                                                                                                                                                                                                     Exception [WinError 995] De I/O-bewerking is afgebroken vanwege het afsluiten van een thread of vanwege een opdracht van een toepassing                Press ENTER to continue...            
````
Sorry, my Windows is in Dutch. If I look in the current folder, I *do* see a folder created with the name `gijs`, and it contains various MonetDB files.

For now, I can work around this by converting the relative path to an absolute path on the windows side.

**Comment by njnes** [comment]
we require an absolute path (I'll add some more checks for this).
